[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; 1. Dice al compilatore dove trovare i file .h
build_flags = 
    -I ../shared

; 2. Dice al compilatore di compilare FISICAMENTE anche i file .cpp condivisi
; Saliamo di due livelli (da src -> master -> cartella principale) per trovare shared
build_src_filter = 
    +<*> 
    +<../../shared/*.cpp>

; 3. Libreria per il chip LoRa SPI
lib_deps = 
    sandeepmistry/LoRa @ ^0.8.0
    olikraus/U8g2 @ ^2.36.2