[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Velocità del monitor seriale per il debug della CLI
monitor_speed = 115200

; Velocità di caricamento del firmware sulla scheda (ottimizzata per ESP32)
upload_speed = 921600

; Fondamentale: dice a PlatformIO dove trovare la cartella dei file condivisi
lib_extra_dirs = ../shared

; Flag di compilazione (facoltativi ma consigliati per il debug)
build_flags = 
    -D CORE_DEBUG_LEVEL=3
