[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; 1. Aggiungiamo la cartella 'shared' ai percorsi in cui cercare i file .h
build_flags = 
    -I ../shared

; 2. Diciamo al compilatore di compilare anche i file .cpp che sono lì dentro
build_src_filter = 
    +<*>
    +<../shared/>

; 3. Le librerie esterne (lascia questa se usi la LilyGO T3)
lib_deps = 
    sandeepmistry/LoRa @ ^0.8.0