[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Velocità del monitor seriale dello slave
monitor_speed = 115200
upload_speed = 921600

; Fondamentale: mappa la stessa cartella shared anche per lo slave
lib_extra_dirs = ../shared

build_flags = 
    -D CORE_DEBUG_LEVEL=3
