name: Build Opus and App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout project code
        uses: actions/checkout@v4

      - name: Clone Opus Source
        run: git clone https://github.com/xiph/opus.git

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            make
            autoconf
            automake
            libtool

      - name: Download miniaudio
        shell: msys2 {0}
        run: |
          curl -L https://raw.githubusercontent.com/mackron/miniaudio/master/miniaudio.h -o ./loracall/miniaudio.h

      - name: Build Opus Library
        shell: msys2 {0}
        run: |
          cd opus
          ./autogen.sh
          ./configure --disable-shared --enable-static
          make -j$(nproc)
          echo "OPUS_PATH=$(pwd)" >> $GITHUB_ENV

      - name: Compile Main Application
        shell: msys2 {0}
        run: |
          gcc -Wall -O2 \
            -I"${{ env.OPUS_PATH }}/include" \
            -I"./loracall" \
            -L"${{ env.OPUS_PATH }}/.libs" \
            ./loracall/loracall.c -o loracall.exe \
            -static \
            -lopus -lwinmm -lole32 -lm

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: loracall.exe

